services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - LOG_LEVEL=debug
      - RELOAD=true
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["uv", "run", "python", "-m", "uvicorn", "kigaprio.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

