services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: kigaprio-backend:dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/uv.lock:/app/uv.lock:ro
    environment:
      - ENV=development
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:5173,http://localhost:8000
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/kigaprio}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    ports:
      - "8000:8000"
    command: uv run uvicorn kigaprio.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - redis
    networks:
      - kigaprio-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: kigaprio-frontend:dev
    volumes:
      # Mount entire frontend directory for hot reload
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from host mount
    environment:
      - PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "5173:5173"  # Vite dev server
    networks:
      - kigaprio-dev

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kigaprio
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kigaprio-dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - kigaprio-dev

volumes:
  postgres-data-dev:

networks:
  kigaprio-dev:
    driver: bridge
