version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: kigaprio-backend-dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/uv.lock:/app/uv.lock:ro
      - frontend-static:/app/static:ro  # Read-only mount of built files
    environment:
      - ENV=development
      - DEBUG=true
      - SERVE_STATIC=true  # Flag to enable static serving
      - CORS_ORIGINS=http://localhost:5173,http://localhost:8000
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/kigaprio}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    ports:
      - "8000:8000"
    command: uv run uvicorn kigaprio.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - redis
    networks:
      - kigaprio-dev

  # Vite dev server for hot-reload development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: kigaprio-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "5173:5173"
    networks:
      - kigaprio-dev

  # Optional: Build frontend periodically for testing static serving
  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    container_name: kigaprio-frontend-builder
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend-static:/app/build
    command: |
      sh -c "
        echo 'Building frontend for static serving...'
        npm run build
        echo 'Build complete! Static files available at http://localhost:8000'
        # Watch for changes and rebuild every 30 seconds (optional)
        while true; do
          sleep 30
          echo 'Rebuilding frontend...'
          npm run build
        done
      "
    networks:
      - kigaprio-dev

  db:
    image: postgres:16-alpine
    container_name: kigaprio-db-dev
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kigaprio
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kigaprio-dev

  redis:
    image: redis:7-alpine
    container_name: kigaprio-redis-dev
    ports:
      - "6379:6379"
    networks:
      - kigaprio-dev

volumes:
  postgres-data-dev:
  frontend-static:

networks:
  kigaprio-dev:
    driver: bridge
