services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: kigaprio-backend:dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/uv.lock:/app/uv.lock:ro
    environment:
      - ENV=development
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:5173,http://localhost:8000
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - POCKETBASE_URL=http://pocketbase:8090
    ports:
      - "8000:8000"
    command: uv run uvicorn kigaprio.main:app --host 0.0.0.0 --port 8000 --reload
    # depends_on:
    #   - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: kigaprio-frontend:dev
    volumes:
      # Mount entire frontend directory for hot reload
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from host mount
    environment:
      - NODE_ENV=development
      - USE_DEV_HTTPS=false
    ports:
      - "5173:5173"  # Vite dev server
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
      args:
        - USER_UID=1000
        - USER_GID=1000
        - PB_VERSION=0.30.0
    image: kigaprio-pocketbase
    restart: unless-stopped
    expose:
      - 8090
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_public:/pb/pb_public
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - pb_admin_email
      - pb_admin_password

secrets:
  pb_admin_email:
    file: ./.secrets/pb_admin_email
  pb_admin_password:
    file: ./.secrets/pb_admin_password

