// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * L​a​d​e​.​.​.
		 */
		loading: string
		/**
		 * F​e​h​l​e​r
		 */
		error: string
		/**
		 * E​r​f​o​l​g
		 */
		success: string
		/**
		 * A​b​b​r​e​c​h​e​n
		 */
		cancel: string
		/**
		 * S​p​e​i​c​h​e​r​n
		 */
		save: string
		/**
		 * L​ö​s​c​h​e​n
		 */
		'delete': string
		/**
		 * B​e​a​r​b​e​i​t​e​n
		 */
		edit: string
		/**
		 * B​e​s​t​ä​t​i​g​e​n
		 */
		confirm: string
		/**
		 * S​c​h​l​i​e​ß​e​n
		 */
		close: string
		/**
		 * J​a
		 */
		yes: string
		/**
		 * N​e​i​n
		 */
		no: string
		/**
		 * A​b​s​e​n​d​e​n
		 */
		submit: string
		/**
		 * Z​u​r​ü​c​k
		 */
		back: string
		/**
		 * W​e​i​t​e​r
		 */
		next: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * P​a​s​s​w​o​r​t
		 */
		password: string
		/**
		 * E​-​M​a​i​l
		 */
		email: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * G​i​t​H​u​b
		 */
		github: string
		/**
		 * I​m​p​r​e​s​s​u​m
		 */
		imprint: string
		/**
		 * D​a​t​e​n​s​c​h​u​t​z
		 */
		privacy: string
	}
	app: {
		/**
		 * P​r​i​o​ ​T​a​g
		 */
		title: string
		/**
		 * P​r​i​o​ ​T​a​g​e​ ​f​ü​r​ ​d​e​n​ ​M​o​n​a​t​ ​f​e​s​t​l​e​g​e​n
		 */
		subtitle: string
	}
	auth: {
		login: {
			/**
			 * A​n​m​e​l​d​e​n
			 */
			title: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​t
			 */
			password: string
			/**
			 * A​n​g​e​m​e​l​d​e​t​ ​b​l​e​i​b​e​n
			 */
			keepLoggedIn: string
			/**
			 * S​i​e​ ​b​l​e​i​b​e​n​ ​3​0​ ​T​a​g​e​ ​a​n​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​p​e​r​s​ö​n​l​i​c​h​e​ ​G​e​r​ä​t​e​.
			 */
			keepLoggedInDesc30Days: string
			/**
			 * S​i​e​ ​w​e​r​d​e​n​ ​n​a​c​h​ ​8​ ​S​t​u​n​d​e​n​ ​o​d​e​r​ ​b​e​i​m​ ​S​c​h​l​i​e​ß​e​n​ ​d​e​s​ ​B​r​o​w​s​e​r​s​ ​a​b​g​e​m​e​l​d​e​t​.​ ​E​m​p​f​o​h​l​e​n​ ​f​ü​r​ ​g​e​m​e​i​n​s​a​m​ ​g​e​n​u​t​z​t​e​ ​C​o​m​p​u​t​e​r​.
			 */
			keepLoggedInDesc8Hours: string
			/**
			 * A​n​m​e​l​d​e​n
			 */
			loginButton: string
			/**
			 * W​i​r​d​ ​a​n​g​e​m​e​l​d​e​t​.​.​.
			 */
			loggingIn: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​e​n
			 */
			registerButton: string
			/**
			 * G​e​s​p​e​i​c​h​e​r​t​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​S​e​r​v​e​r​s​e​i​t​i​g​ ​v​e​r​s​c​h​l​ü​s​s​e​l​t​.​ ​W​i​r​ ​k​ö​n​n​e​n​ ​I​h​r​e​ ​p​e​r​s​ö​n​l​i​c​h​e​n​ ​I​n​f​o​r​m​a​t​i​o​n​e​n​ ​n​i​c​h​t​ ​l​e​s​e​n​.
			 */
			securityNote: string
		}
		register: {
			/**
			 * R​e​g​i​s​t​r​i​e​r​e​n
			 */
			title: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​t
			 */
			password: string
			/**
			 * P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
			 */
			passwordConfirm: string
			/**
			 * V​o​l​l​s​t​ä​n​d​i​g​e​r​ ​N​a​m​e
			 */
			fullName: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t
			 */
			magicWord: string
			/**
			 * A​n​g​e​m​e​l​d​e​t​ ​b​l​e​i​b​e​n
			 */
			keepLoggedIn: string
			/**
			 * R​e​g​i​s​t​r​i​e​r​e​n
			 */
			registerButton: string
			/**
			 * W​i​r​d​ ​r​e​g​i​s​t​r​i​e​r​t​.​.​.
			 */
			registering: string
			/**
			 * Z​u​r​ü​c​k​ ​z​u​m​ ​L​o​g​i​n
			 */
			backToLogin: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			magicWordPlaceholder: string
			/**
			 * Z​a​u​b​e​r​w​o​r​t​ ​v​e​r​i​f​i​z​i​e​r​e​n
			 */
			verifyMagicWord: string
			/**
			 * W​i​r​d​ ​v​e​r​i​f​i​z​i​e​r​t​.​.​.
			 */
			verifying: string
			/**
			 * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
			 */
			errorPasswordMismatch: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​1​ ​c​h​a​r​a​c​t​e​r​ ​l​o​n​g
			 */
			errorPasswordTooShort: string
			/**
			 * U​n​g​ü​l​t​i​g​e​s​ ​Z​a​u​b​e​r​w​o​r​t
			 */
			errorInvalidMagicWord: string
			/**
			 * Q​R​-​C​o​d​e​ ​R​e​g​i​s​t​r​i​e​r​u​n​g
			 */
			qrCodeRegistration: string
			/**
			 * N​o​r​m​a​l​e​ ​R​e​g​i​s​t​r​i​e​r​u​n​g
			 */
			traditionalRegistration: string
		}
		/**
		 * A​b​m​e​l​d​e​n
		 */
		logout: string
		reauth: {
			/**
			 * E​r​n​e​u​t​e​ ​A​n​m​e​l​d​u​n​g​ ​e​r​f​o​r​d​e​r​l​i​c​h
			 */
			title: string
			/**
			 * I​h​r​e​ ​S​i​t​z​u​n​g​ ​i​s​t​ ​a​b​g​e​l​a​u​f​e​n​.​ ​B​i​t​t​e​ ​m​e​l​d​e​n​ ​S​i​e​ ​s​i​c​h​ ​e​r​n​e​u​t​ ​a​n​.
			 */
			message: string
			/**
			 * P​a​s​s​w​o​r​t​ ​e​i​n​g​e​b​e​n
			 */
			passwordPlaceholder: string
			/**
			 * A​n​m​e​l​d​e​n
			 */
			loginButton: string
			/**
			 * A​b​b​r​e​c​h​e​n
			 */
			cancelButton: string
		}
	}
	priorities: {
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n
		 */
		title: string
		labels: {
			/**
			 * S​e​h​r​ ​w​i​c​h​t​i​g
			 */
			veryImportant: string
			/**
			 * W​i​c​h​t​i​g
			 */
			important: string
			/**
			 * N​o​r​m​a​l
			 */
			normal: string
			/**
			 * W​e​n​i​g​e​r​ ​w​i​c​h​t​i​g
			 */
			lessImportant: string
			/**
			 * U​n​w​i​c​h​t​i​g
			 */
			unimportant: string
		}
		days: {
			/**
			 * M​o​n​t​a​g
			 */
			monday: string
			/**
			 * D​i​e​n​s​t​a​g
			 */
			tuesday: string
			/**
			 * M​i​t​t​w​o​c​h
			 */
			wednesday: string
			/**
			 * D​o​n​n​e​r​s​t​a​g
			 */
			thursday: string
			/**
			 * F​r​e​i​t​a​g
			 */
			friday: string
		}
		/**
		 * M​o​n​a​t​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectMonth: string
		/**
		 * J​a​h​r​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectYear: string
		/**
		 * A​k​t​u​e​l​l​e​r​ ​M​o​n​a​t
		 */
		currentMonth: string
		/**
		 * Ä​n​d​e​r​u​n​g​e​n​ ​s​p​e​i​c​h​e​r​n
		 */
		saveChanges: string
		/**
		 * W​i​r​d​ ​g​e​s​p​e​i​c​h​e​r​t​.​.​.
		 */
		saving: string
		/**
		 * G​e​s​p​e​i​c​h​e​r​t
		 */
		saved: string
		/**
		 * F​e​h​l​e​r​ ​b​e​i​m​ ​S​p​e​i​c​h​e​r​n
		 */
		errorSaving: string
		/**
		 * K​e​i​n​e​ ​D​a​t​e​n​ ​f​ü​r​ ​d​i​e​s​e​n​ ​M​o​n​a​t
		 */
		noDataForMonth: string
		/**
		 * K​l​i​c​k​e​n​ ​S​i​e​,​ ​u​m​ ​d​i​e​ ​P​r​i​o​r​i​t​ä​t​ ​z​u​ ​s​e​t​z​e​n
		 */
		clickToSetPriority: string
		/**
		 * F​e​i​e​r​t​a​g
		 */
		holiday: string
		/**
		 * U​r​l​a​u​b
		 */
		vacation: string
		/**
		 * W​o​c​h​e​n​e​n​d​e
		 */
		weekend: string
	}
	dashboard: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		title: string
		/**
		 * W​i​l​l​k​o​m​m​e​n​ ​z​u​r​ü​c​k
		 */
		welcome: string
		/**
		 * Ü​b​e​r​s​i​c​h​t
		 */
		overview: string
		/**
		 * S​t​a​t​i​s​t​i​k​e​n
		 */
		statistics: string
		/**
		 * L​e​t​z​t​e​ ​A​k​t​i​v​i​t​ä​t
		 */
		recentActivity: string
		/**
		 * K​e​i​n​e​ ​P​r​i​o​r​i​t​ä​t​e​n​ ​g​e​s​e​t​z​t
		 */
		noPrioritiesSet: string
		/**
		 * P​r​i​o​r​i​t​ä​t​e​n​ ​s​e​t​z​e​n
		 */
		setPriorities: string
		/**
		 * D​i​e​s​e​n​ ​M​o​n​a​t
		 */
		thisMonth: string
		/**
		 * D​i​e​s​e​ ​W​o​c​h​e
		 */
		thisWeek: string
		/**
		 * H​e​u​t​e
		 */
		today: string
		/**
		 * K​o​m​m​e​n​d​e​r​ ​U​r​l​a​u​b
		 */
		upcomingVacation: string
		/**
		 * K​e​i​n​ ​k​o​m​m​e​n​d​e​r​ ​U​r​l​a​u​b
		 */
		noUpcomingVacation: string
	}
	account: {
		/**
		 * K​o​n​t​o
		 */
		title: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		settings: string
		/**
		 * P​r​o​f​i​l
		 */
		profile: string
		/**
		 * S​i​c​h​e​r​h​e​i​t
		 */
		security: string
		/**
		 * E​i​n​s​t​e​l​l​u​n​g​e​n
		 */
		preferences: string
		/**
		 * S​p​r​a​c​h​e
		 */
		language: string
		/**
		 * S​p​r​a​c​h​e​ ​a​u​s​w​ä​h​l​e​n
		 */
		selectLanguage: string
		/**
		 * P​a​s​s​w​o​r​t​ ​ä​n​d​e​r​n
		 */
		changePassword: string
		/**
		 * A​k​t​u​e​l​l​e​s​ ​P​a​s​s​w​o​r​t
		 */
		currentPassword: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t
		 */
		newPassword: string
		/**
		 * N​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
		 */
		confirmNewPassword: string
		/**
		 * P​r​o​f​i​l​ ​a​k​t​u​a​l​i​s​i​e​r​e​n
		 */
		updateProfile: string
		/**
		 * K​o​n​t​o​ ​l​ö​s​c​h​e​n
		 */
		deleteAccount: string
		/**
		 * M​ö​c​h​t​e​n​ ​S​i​e​ ​I​h​r​ ​K​o​n​t​o​ ​w​i​r​k​l​i​c​h​ ​l​ö​s​c​h​e​n​?​ ​D​i​e​s​e​ ​A​k​t​i​o​n​ ​k​a​n​n​ ​n​i​c​h​t​ ​r​ü​c​k​g​ä​n​g​i​g​ ​g​e​m​a​c​h​t​ ​w​e​r​d​e​n​.
		 */
		deleteAccountConfirm: string
	}
	vacation: {
		/**
		 * U​r​l​a​u​b
		 */
		title: string
		/**
		 * U​r​l​a​u​b​ ​h​i​n​z​u​f​ü​g​e​n
		 */
		addVacation: string
		/**
		 * U​r​l​a​u​b​ ​b​e​a​r​b​e​i​t​e​n
		 */
		editVacation: string
		/**
		 * U​r​l​a​u​b​ ​l​ö​s​c​h​e​n
		 */
		deleteVacation: string
		/**
		 * S​t​a​r​t​d​a​t​u​m
		 */
		startDate: string
		/**
		 * E​n​d​d​a​t​u​m
		 */
		endDate: string
		/**
		 * T​a​g​e
		 */
		days: string
		/**
		 * G​e​s​a​m​t​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		totalVacationDays: string
		/**
		 * V​e​r​b​l​e​i​b​e​n​d​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		remainingVacationDays: string
		/**
		 * G​e​n​u​t​z​t​e​ ​U​r​l​a​u​b​s​t​a​g​e
		 */
		usedVacationDays: string
	}
	notifications: {
		/**
		 * B​e​n​a​c​h​r​i​c​h​t​i​g​u​n​g​e​n
		 */
		title: string
		/**
		 * K​e​i​n​e​ ​B​e​n​a​c​h​r​i​c​h​t​i​g​u​n​g​e​n
		 */
		noNotifications: string
		/**
		 * A​l​s​ ​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
		 */
		markAsRead: string
		/**
		 * A​l​l​e​ ​a​l​s​ ​g​e​l​e​s​e​n​ ​m​a​r​k​i​e​r​e​n
		 */
		markAllAsRead: string
		/**
		 * A​l​l​e​ ​l​ö​s​c​h​e​n
		 */
		clearAll: string
	}
	errors: {
		/**
		 * E​i​n​ ​F​e​h​l​e​r​ ​i​s​t​ ​a​u​f​g​e​t​r​e​t​e​n
		 */
		general: string
		/**
		 * N​e​t​z​w​e​r​k​f​e​h​l​e​r
		 */
		networkError: string
		/**
		 * S​e​r​v​e​r​f​e​h​l​e​r
		 */
		serverError: string
		/**
		 * N​i​c​h​t​ ​g​e​f​u​n​d​e​n
		 */
		notFound: string
		/**
		 * N​i​c​h​t​ ​a​u​t​o​r​i​s​i​e​r​t
		 */
		unauthorized: string
		/**
		 * V​e​r​b​o​t​e​n
		 */
		forbidden: string
		/**
		 * V​a​l​i​d​i​e​r​u​n​g​s​f​e​h​l​e​r
		 */
		validationError: string
		/**
		 * S​i​t​z​u​n​g​ ​a​b​g​e​l​a​u​f​e​n
		 */
		sessionExpired: string
		/**
		 * A​n​m​e​l​d​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 */
		loginFailed: string
		/**
		 * R​e​g​i​s​t​r​i​e​r​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
		 */
		registrationFailed: string
		/**
		 * U​n​g​ü​l​t​i​g​e​ ​A​n​m​e​l​d​e​d​a​t​e​n
		 */
		invalidCredentials: string
		/**
		 * B​e​n​u​t​z​e​r​ ​e​x​i​s​t​i​e​r​t​ ​b​e​r​e​i​t​s
		 */
		userAlreadyExists: string
		/**
		 * P​a​s​s​w​o​r​t​ ​z​u​ ​k​u​r​z
		 */
		passwordTooShort: string
		/**
		 * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n
		 */
		passwordMismatch: string
		/**
		 * D​i​e​s​e​s​ ​F​e​l​d​ ​i​s​t​ ​e​r​f​o​r​d​e​r​l​i​c​h
		 */
		requiredField: string
		/**
		 * U​n​g​ü​l​t​i​g​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e
		 */
		invalidEmail: string
		/**
		 * U​n​g​ü​l​t​i​g​e​s​ ​D​a​t​u​m
		 */
		invalidDate: string
		/**
		 * B​i​t​t​e​ ​v​e​r​s​u​c​h​e​n​ ​S​i​e​ ​e​s​ ​e​r​n​e​u​t
		 */
		tryAgain: string
	}
	success: {
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​g​e​s​p​e​i​c​h​e​r​t
		 */
		saved: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​k​t​u​a​l​i​s​i​e​r​t
		 */
		updated: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​g​e​l​ö​s​c​h​t
		 */
		deleted: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​e​r​s​t​e​l​l​t
		 */
		created: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​n​g​e​m​e​l​d​e​t
		 */
		loginSuccess: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​a​b​g​e​m​e​l​d​e​t
		 */
		logoutSuccess: string
		/**
		 * E​r​f​o​l​g​r​e​i​c​h​ ​r​e​g​i​s​t​r​i​e​r​t
		 */
		registrationSuccess: string
		/**
		 * P​a​s​s​w​o​r​t​ ​e​r​f​o​l​g​r​e​i​c​h​ ​g​e​ä​n​d​e​r​t
		 */
		passwordChanged: string
		/**
		 * P​r​o​f​i​l​ ​e​r​f​o​l​g​r​e​i​c​h​ ​a​k​t​u​a​l​i​s​i​e​r​t
		 */
		profileUpdated: string
	}
	admin: {
		/**
		 * A​d​m​i​n
		 */
		title: string
		/**
		 * A​d​m​i​n​ ​D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Lade...
		 */
		loading: () => LocalizedString
		/**
		 * Fehler
		 */
		error: () => LocalizedString
		/**
		 * Erfolg
		 */
		success: () => LocalizedString
		/**
		 * Abbrechen
		 */
		cancel: () => LocalizedString
		/**
		 * Speichern
		 */
		save: () => LocalizedString
		/**
		 * Löschen
		 */
		'delete': () => LocalizedString
		/**
		 * Bearbeiten
		 */
		edit: () => LocalizedString
		/**
		 * Bestätigen
		 */
		confirm: () => LocalizedString
		/**
		 * Schließen
		 */
		close: () => LocalizedString
		/**
		 * Ja
		 */
		yes: () => LocalizedString
		/**
		 * Nein
		 */
		no: () => LocalizedString
		/**
		 * Absenden
		 */
		submit: () => LocalizedString
		/**
		 * Zurück
		 */
		back: () => LocalizedString
		/**
		 * Weiter
		 */
		next: () => LocalizedString
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Passwort
		 */
		password: () => LocalizedString
		/**
		 * E-Mail
		 */
		email: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * GitHub
		 */
		github: () => LocalizedString
		/**
		 * Impressum
		 */
		imprint: () => LocalizedString
		/**
		 * Datenschutz
		 */
		privacy: () => LocalizedString
	}
	app: {
		/**
		 * Prio Tag
		 */
		title: () => LocalizedString
		/**
		 * Prio Tage für den Monat festlegen
		 */
		subtitle: () => LocalizedString
	}
	auth: {
		login: {
			/**
			 * Anmelden
			 */
			title: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Passwort
			 */
			password: () => LocalizedString
			/**
			 * Angemeldet bleiben
			 */
			keepLoggedIn: () => LocalizedString
			/**
			 * Sie bleiben 30 Tage angemeldet. Empfohlen für persönliche Geräte.
			 */
			keepLoggedInDesc30Days: () => LocalizedString
			/**
			 * Sie werden nach 8 Stunden oder beim Schließen des Browsers abgemeldet. Empfohlen für gemeinsam genutzte Computer.
			 */
			keepLoggedInDesc8Hours: () => LocalizedString
			/**
			 * Anmelden
			 */
			loginButton: () => LocalizedString
			/**
			 * Wird angemeldet...
			 */
			loggingIn: () => LocalizedString
			/**
			 * Registrieren
			 */
			registerButton: () => LocalizedString
			/**
			 * Gespeicherte Daten werden Serverseitig verschlüsselt. Wir können Ihre persönlichen Informationen nicht lesen.
			 */
			securityNote: () => LocalizedString
		}
		register: {
			/**
			 * Registrieren
			 */
			title: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Passwort
			 */
			password: () => LocalizedString
			/**
			 * Passwort bestätigen
			 */
			passwordConfirm: () => LocalizedString
			/**
			 * Vollständiger Name
			 */
			fullName: () => LocalizedString
			/**
			 * Zauberwort
			 */
			magicWord: () => LocalizedString
			/**
			 * Angemeldet bleiben
			 */
			keepLoggedIn: () => LocalizedString
			/**
			 * Registrieren
			 */
			registerButton: () => LocalizedString
			/**
			 * Wird registriert...
			 */
			registering: () => LocalizedString
			/**
			 * Zurück zum Login
			 */
			backToLogin: () => LocalizedString
			/**
			 * Zauberwort eingeben
			 */
			magicWordPlaceholder: () => LocalizedString
			/**
			 * Zauberwort verifizieren
			 */
			verifyMagicWord: () => LocalizedString
			/**
			 * Wird verifiziert...
			 */
			verifying: () => LocalizedString
			/**
			 * Passwörter stimmen nicht überein
			 */
			errorPasswordMismatch: () => LocalizedString
			/**
			 * Password must be at least 1 character long
			 */
			errorPasswordTooShort: () => LocalizedString
			/**
			 * Ungültiges Zauberwort
			 */
			errorInvalidMagicWord: () => LocalizedString
			/**
			 * QR-Code Registrierung
			 */
			qrCodeRegistration: () => LocalizedString
			/**
			 * Normale Registrierung
			 */
			traditionalRegistration: () => LocalizedString
		}
		/**
		 * Abmelden
		 */
		logout: () => LocalizedString
		reauth: {
			/**
			 * Erneute Anmeldung erforderlich
			 */
			title: () => LocalizedString
			/**
			 * Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.
			 */
			message: () => LocalizedString
			/**
			 * Passwort eingeben
			 */
			passwordPlaceholder: () => LocalizedString
			/**
			 * Anmelden
			 */
			loginButton: () => LocalizedString
			/**
			 * Abbrechen
			 */
			cancelButton: () => LocalizedString
		}
	}
	priorities: {
		/**
		 * Prioritäten
		 */
		title: () => LocalizedString
		labels: {
			/**
			 * Sehr wichtig
			 */
			veryImportant: () => LocalizedString
			/**
			 * Wichtig
			 */
			important: () => LocalizedString
			/**
			 * Normal
			 */
			normal: () => LocalizedString
			/**
			 * Weniger wichtig
			 */
			lessImportant: () => LocalizedString
			/**
			 * Unwichtig
			 */
			unimportant: () => LocalizedString
		}
		days: {
			/**
			 * Montag
			 */
			monday: () => LocalizedString
			/**
			 * Dienstag
			 */
			tuesday: () => LocalizedString
			/**
			 * Mittwoch
			 */
			wednesday: () => LocalizedString
			/**
			 * Donnerstag
			 */
			thursday: () => LocalizedString
			/**
			 * Freitag
			 */
			friday: () => LocalizedString
		}
		/**
		 * Monat auswählen
		 */
		selectMonth: () => LocalizedString
		/**
		 * Jahr auswählen
		 */
		selectYear: () => LocalizedString
		/**
		 * Aktueller Monat
		 */
		currentMonth: () => LocalizedString
		/**
		 * Änderungen speichern
		 */
		saveChanges: () => LocalizedString
		/**
		 * Wird gespeichert...
		 */
		saving: () => LocalizedString
		/**
		 * Gespeichert
		 */
		saved: () => LocalizedString
		/**
		 * Fehler beim Speichern
		 */
		errorSaving: () => LocalizedString
		/**
		 * Keine Daten für diesen Monat
		 */
		noDataForMonth: () => LocalizedString
		/**
		 * Klicken Sie, um die Priorität zu setzen
		 */
		clickToSetPriority: () => LocalizedString
		/**
		 * Feiertag
		 */
		holiday: () => LocalizedString
		/**
		 * Urlaub
		 */
		vacation: () => LocalizedString
		/**
		 * Wochenende
		 */
		weekend: () => LocalizedString
	}
	dashboard: {
		/**
		 * Dashboard
		 */
		title: () => LocalizedString
		/**
		 * Willkommen zurück
		 */
		welcome: () => LocalizedString
		/**
		 * Übersicht
		 */
		overview: () => LocalizedString
		/**
		 * Statistiken
		 */
		statistics: () => LocalizedString
		/**
		 * Letzte Aktivität
		 */
		recentActivity: () => LocalizedString
		/**
		 * Keine Prioritäten gesetzt
		 */
		noPrioritiesSet: () => LocalizedString
		/**
		 * Prioritäten setzen
		 */
		setPriorities: () => LocalizedString
		/**
		 * Diesen Monat
		 */
		thisMonth: () => LocalizedString
		/**
		 * Diese Woche
		 */
		thisWeek: () => LocalizedString
		/**
		 * Heute
		 */
		today: () => LocalizedString
		/**
		 * Kommender Urlaub
		 */
		upcomingVacation: () => LocalizedString
		/**
		 * Kein kommender Urlaub
		 */
		noUpcomingVacation: () => LocalizedString
	}
	account: {
		/**
		 * Konto
		 */
		title: () => LocalizedString
		/**
		 * Einstellungen
		 */
		settings: () => LocalizedString
		/**
		 * Profil
		 */
		profile: () => LocalizedString
		/**
		 * Sicherheit
		 */
		security: () => LocalizedString
		/**
		 * Einstellungen
		 */
		preferences: () => LocalizedString
		/**
		 * Sprache
		 */
		language: () => LocalizedString
		/**
		 * Sprache auswählen
		 */
		selectLanguage: () => LocalizedString
		/**
		 * Passwort ändern
		 */
		changePassword: () => LocalizedString
		/**
		 * Aktuelles Passwort
		 */
		currentPassword: () => LocalizedString
		/**
		 * Neues Passwort
		 */
		newPassword: () => LocalizedString
		/**
		 * Neues Passwort bestätigen
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * Profil aktualisieren
		 */
		updateProfile: () => LocalizedString
		/**
		 * Konto löschen
		 */
		deleteAccount: () => LocalizedString
		/**
		 * Möchten Sie Ihr Konto wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.
		 */
		deleteAccountConfirm: () => LocalizedString
	}
	vacation: {
		/**
		 * Urlaub
		 */
		title: () => LocalizedString
		/**
		 * Urlaub hinzufügen
		 */
		addVacation: () => LocalizedString
		/**
		 * Urlaub bearbeiten
		 */
		editVacation: () => LocalizedString
		/**
		 * Urlaub löschen
		 */
		deleteVacation: () => LocalizedString
		/**
		 * Startdatum
		 */
		startDate: () => LocalizedString
		/**
		 * Enddatum
		 */
		endDate: () => LocalizedString
		/**
		 * Tage
		 */
		days: () => LocalizedString
		/**
		 * Gesamte Urlaubstage
		 */
		totalVacationDays: () => LocalizedString
		/**
		 * Verbleibende Urlaubstage
		 */
		remainingVacationDays: () => LocalizedString
		/**
		 * Genutzte Urlaubstage
		 */
		usedVacationDays: () => LocalizedString
	}
	notifications: {
		/**
		 * Benachrichtigungen
		 */
		title: () => LocalizedString
		/**
		 * Keine Benachrichtigungen
		 */
		noNotifications: () => LocalizedString
		/**
		 * Als gelesen markieren
		 */
		markAsRead: () => LocalizedString
		/**
		 * Alle als gelesen markieren
		 */
		markAllAsRead: () => LocalizedString
		/**
		 * Alle löschen
		 */
		clearAll: () => LocalizedString
	}
	errors: {
		/**
		 * Ein Fehler ist aufgetreten
		 */
		general: () => LocalizedString
		/**
		 * Netzwerkfehler
		 */
		networkError: () => LocalizedString
		/**
		 * Serverfehler
		 */
		serverError: () => LocalizedString
		/**
		 * Nicht gefunden
		 */
		notFound: () => LocalizedString
		/**
		 * Nicht autorisiert
		 */
		unauthorized: () => LocalizedString
		/**
		 * Verboten
		 */
		forbidden: () => LocalizedString
		/**
		 * Validierungsfehler
		 */
		validationError: () => LocalizedString
		/**
		 * Sitzung abgelaufen
		 */
		sessionExpired: () => LocalizedString
		/**
		 * Anmeldung fehlgeschlagen
		 */
		loginFailed: () => LocalizedString
		/**
		 * Registrierung fehlgeschlagen
		 */
		registrationFailed: () => LocalizedString
		/**
		 * Ungültige Anmeldedaten
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * Benutzer existiert bereits
		 */
		userAlreadyExists: () => LocalizedString
		/**
		 * Passwort zu kurz
		 */
		passwordTooShort: () => LocalizedString
		/**
		 * Passwörter stimmen nicht überein
		 */
		passwordMismatch: () => LocalizedString
		/**
		 * Dieses Feld ist erforderlich
		 */
		requiredField: () => LocalizedString
		/**
		 * Ungültige E-Mail-Adresse
		 */
		invalidEmail: () => LocalizedString
		/**
		 * Ungültiges Datum
		 */
		invalidDate: () => LocalizedString
		/**
		 * Bitte versuchen Sie es erneut
		 */
		tryAgain: () => LocalizedString
	}
	success: {
		/**
		 * Erfolgreich gespeichert
		 */
		saved: () => LocalizedString
		/**
		 * Erfolgreich aktualisiert
		 */
		updated: () => LocalizedString
		/**
		 * Erfolgreich gelöscht
		 */
		deleted: () => LocalizedString
		/**
		 * Erfolgreich erstellt
		 */
		created: () => LocalizedString
		/**
		 * Erfolgreich angemeldet
		 */
		loginSuccess: () => LocalizedString
		/**
		 * Erfolgreich abgemeldet
		 */
		logoutSuccess: () => LocalizedString
		/**
		 * Erfolgreich registriert
		 */
		registrationSuccess: () => LocalizedString
		/**
		 * Passwort erfolgreich geändert
		 */
		passwordChanged: () => LocalizedString
		/**
		 * Profil erfolgreich aktualisiert
		 */
		profileUpdated: () => LocalizedString
	}
	admin: {
		/**
		 * Admin
		 */
		title: () => LocalizedString
		/**
		 * Admin Dashboard
		 */
		dashboard: () => LocalizedString
	}
}

export type Formatters = {}
